### PR TITLE
agent: honour listen-only-* flags

### PR DESCRIPTION
**Pull request by ymartin-ovh**
Fix incorrect settings read, does not match cli config in the same file

### CODE REVIEW

**Comment by ymartin-ovh** [comment]
Address issue #3

**Comment by vrisk** [comment]
Hi - this is really a read-only copy of our working repository. It is not actively monitored. Can you put your issues into our working repo at https://gitlab.isc.org/isc-projects/stork/-/issues?

Thank you!

**Comment by ymartin-ovh** [comment]
https://gitlab.isc.org/isc-projects/stork/-/issues/536

**Comment by fivitti** [comment]
It was merged in https://gitlab.isc.org/isc-projects/stork/-/issues/536 by https://gitlab.isc.org/isc-projects/stork/-/merge_requests/310 MR.

**Pull request closed without merging**
